run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplifies code
    - govet         # Examines Go source code and reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis checks
    - typecheck     # Type-checks Go code
    - unused        # Checks for unused constants, variables, functions and types
    - gofmt         # Checks whether code was gofmt-ed
    - goimports     # Checks import statements are formatted
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gosec         # Inspects source code for security problems
    - bodyclose     # Checks whether HTTP response body is closed successfully
    - nilerr        # Finds code that returns nil even if it checks that the error is not nil

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadow
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
  max-issues-per-linter: 0
  max-same-issues: 0
  
output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
